before:
  hooks:
  - go mod download
  - go-licenses save github.com/claudio4/cloudflare-ddns/cmd/cloudflare-ddns --save_path=LICENSES
builds:
  -
    main: cmd/cloudflare-ddns/main.go
    binary: cloudflare-ddns
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
